[[sed]]
arch = "aarch64"
git-tree-sha1 = "ff4aa5125f564390766ab42838415202d69aff2f"
os = "macos"

    [[sed.download]]
    sha256 = "ab89782ce88a67eac28ade75294d72f6f3abc61ceb80e7e5ee1a84d51691870e"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.aarch64-apple-darwin.tar.gz"
[[sed]]
arch = "aarch64"
git-tree-sha1 = "2f8e52f9443842518f8af5348078b929605ad23a"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "c2cf88ac41dc5db3e48f116717d21a82d215feefd9ec86d4253312cd6b39a4ea"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.aarch64-linux-gnu.tar.gz"
[[sed]]
arch = "aarch64"
git-tree-sha1 = "8b5b395347f7d2296099062a04d803c1a867a86e"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "126bbca64a9834ba7e4b92dccffd5117bf234e094dc80de6f9e88b54bf9a88a8"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.aarch64-linux-musl.tar.gz"
[[sed]]
arch = "aarch64"
git-tree-sha1 = "d424554d265ea75f4fe6270c771c55ce38400af7"
os = "freebsd"

    [[sed.download]]
    sha256 = "1cc8123340698e3fa5533d1b22497b78f55ca5d79f22dee1a519e7da1933ac87"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.aarch64-unknown-freebsd.tar.gz"
[[sed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "483d6d02164bb92a151b374c47d528f32e48b748"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "9121dcf2b59b2138dfa7e9a27f60bf8c23e7816cdfef354ce5edefc539d21e5c"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.armv6l-linux-gnueabihf.tar.gz"
[[sed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3790b358cde54a672126cbb2a40fc3940c9c938"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "14c7a6559be0bd506232bb80f86d796c517dc8a526665606ec63001e21f08848"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.armv6l-linux-musleabihf.tar.gz"
[[sed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "990143de760b9f1e126c4076ebbda0fbee77966e"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "4657bfcf1eb4eed61ed862599ee2b2007365c9cea885748a693b12686610b3f1"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.armv7l-linux-gnueabihf.tar.gz"
[[sed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3da769a8afe2bab24a9536698c0a9932bf56e974"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "a13ab25b9056edc9ddaad22d2c1b3054d9c64efd196940726b31459ece49916d"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.armv7l-linux-musleabihf.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "cbef6ac056544810f6c15034f51b914d5bd5e86e"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "3670e00e1075b09f5362722dc343b28c766e16f7250e2a6303c8a003d77e1ebc"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.i686-linux-gnu.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "493e556f119aad209be79c2d9e4ae292f7de2eb1"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "da70ab0daae28a87c792258ccf244920c6753b7f8f61596e124a3d4f2b57342b"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.i686-linux-musl.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "fe48d268ddec7fe54c431c79660137994a64e699"
os = "windows"

    [[sed.download]]
    sha256 = "05e923607a83f12e68c199514b0ffcf08abfddcf4e4dcc8a19dee3ffb3faae42"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.i686-w64-mingw32.tar.gz"
[[sed]]
arch = "powerpc64le"
git-tree-sha1 = "14221cbd744e8c3fb67a0e83ed01c34d2ea6fd52"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "445f6134636d5c4adee96f4362512996ca804ca14ab62da6d26dc62bab60b374"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.powerpc64le-linux-gnu.tar.gz"
[[sed]]
arch = "riscv64"
git-tree-sha1 = "0f5bdf3a6f5605a15354a5f8ccbe274be5f7f8b7"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "00a58d514752b3d67f7c8082f95363528e7a42b052ab79d0d16181ae9f6a6d8d"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.riscv64-linux-gnu.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "ff9da057041b97abddf90ac2daade0f024db10d0"
os = "macos"

    [[sed.download]]
    sha256 = "21d02b23b5b5484eb8f2355f0bf8dbd1f334dd55eba3400a44ca1ade2264ba05"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.x86_64-apple-darwin.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "c00859160fdef77e1e68694ddd6812aa262e789c"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "68f7f1b0dcfa14fca005db9291ed1e58064f8b0bcbc606ceae9fa0c72695deb4"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.x86_64-linux-gnu.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "be11a83f8caba32387b6ac4a17030c3a1938a1e2"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "fec10e99c3c5b5eb88fb1c0f7c91c8805a2dbc65eedcd5b0311d3b85d1a4466f"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.x86_64-linux-musl.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "7e952d2df2ccbe210b6ee50a05a170a366340229"
os = "freebsd"

    [[sed.download]]
    sha256 = "c60148ca7cacab5f8aeccb2bef3ffe282e87b3cea2f4b783ebe906e621f4be44"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.x86_64-unknown-freebsd.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "33a52de67875a6f163d8490368989e9a16297a5a"
os = "windows"

    [[sed.download]]
    sha256 = "b8c5fd28678343a077829c11cadbbe6fdaa09e6aae0ae90f6b7b062cfbf065ef"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.10.0+0/sed.v4.10.0.x86_64-w64-mingw32.tar.gz"
