[[sed]]
arch = "aarch64"
git-tree-sha1 = "ee43f4badbe3c9adc7e3e3172593a9c308ec7f08"
os = "macos"

    [[sed.download]]
    sha256 = "73889386aeb4211e397d4934e15d07ebd32497f64c3e48e3d62bbdabd88aeb76"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.aarch64-apple-darwin.tar.gz"
[[sed]]
arch = "aarch64"
git-tree-sha1 = "1ea552cad76a4d191a5b2dd4b5fc45e5de630cb2"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "9874eaa79bab7478e9b677cffb7dc13f3285e0899457fc206f36f1114a947c04"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.aarch64-linux-gnu.tar.gz"
[[sed]]
arch = "aarch64"
git-tree-sha1 = "d9e2c57c4c4e172464c3943c3d42d27685b3732b"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "5e9d52b91c39d6e486fa4f3469a87adc3b606e7c8fe45c1902cf73436571d4e8"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.aarch64-linux-musl.tar.gz"
[[sed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16183ef64e0e26f2e834dae89555e510dfbc9d4e"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "04ae98475cac9186b2163d6653e021b450f2d7b95514afad39ae14ed3f2ee3da"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.armv6l-linux-gnueabihf.tar.gz"
[[sed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "74aa0b11becdc1d66955b9029da216eed2b5a95f"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "d9f23724f5bfed5368864f913aa14b91cc40d2896d9af4299ff78087ae40cd65"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.armv6l-linux-musleabihf.tar.gz"
[[sed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7da475ceeeff5e14d9c5d01a6fdfeb2880048481"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "8848f58b47adaaefc163ed75eec8751d9c7f492f8b030929f6d99b90285c2cf3"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.armv7l-linux-gnueabihf.tar.gz"
[[sed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "678cb1222ffec4c7f1c446489fe595263b3e815c"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "6f5ce254f53732fa1de69c570af6fe2e854bb77d92f1832c8f3e3445f8a8a7c3"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.armv7l-linux-musleabihf.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "90c9a13883b65b4cc03d8ed72405d415ff1da000"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "d2d1f0f87f43d0782b38302948a397b8dbe1cfd8c513ed7cc0588cff40550ee0"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.i686-linux-gnu.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "4ad807c01b79a9b5679e9d8dc44bd4fe124244ee"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "93d66bf98302fadd5a065a48bf3a245d8eacd4af9fdda06602adfd8baf1ac72d"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.i686-linux-musl.tar.gz"
[[sed]]
arch = "i686"
git-tree-sha1 = "71f92d2c7b5f14cee404e0c77042e7d35ba49217"
os = "windows"

    [[sed.download]]
    sha256 = "50cc91ad2199d30287ede943d6ae325b30aa2505270fc6e55276b7500e1c8cb2"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.i686-w64-mingw32.tar.gz"
[[sed]]
arch = "powerpc64le"
git-tree-sha1 = "614e67db145db02f916f5cc85683fb2aaf511fb2"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "cc5358965a68047846cdc3bf6b281d166e928c6c71f08b1787868b765378fdb7"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.powerpc64le-linux-gnu.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "1f765dcd53cd43a3126d97521aeda3d0c032470a"
os = "macos"

    [[sed.download]]
    sha256 = "7882735d53087e5c01e9ff97bf925bdbb81a1bffe3b5aa812ffa2aa8bf8f2948"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.x86_64-apple-darwin.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "3126135d50b6c13ae5f950fa9a1902d181ed6bce"
libc = "glibc"
os = "linux"

    [[sed.download]]
    sha256 = "b88670dda7ae8ba77eedd1b5e8b80417b09cc6d868c337b8f26f007380d2bd03"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.x86_64-linux-gnu.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "435433cf3e4349d09dbe9c61d5b457717ad78b10"
libc = "musl"
os = "linux"

    [[sed.download]]
    sha256 = "80d1b4da5fe3da85a8529989467407910c0d5751b1159092001329876112a1b2"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.x86_64-linux-musl.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "bd25805597843da888a0f86af7de2f2165dab88e"
os = "freebsd"

    [[sed.download]]
    sha256 = "211a5d72009cff6d02e7c61c00ea7ae3d997d057d1bb7e34e5fd0070042cc65f"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.x86_64-unknown-freebsd.tar.gz"
[[sed]]
arch = "x86_64"
git-tree-sha1 = "f96966b06aaa7c57a5a80c2dd9f08f2f29235270"
os = "windows"

    [[sed.download]]
    sha256 = "35f7b6e80706f3a92fa569ffee25682a9f9c15543156ca47cffed48f60c3697a"
    url = "https://github.com/JuliaBinaryWrappers/sed_jll.jl/releases/download/sed-v4.8.1+0/sed.v4.8.1.x86_64-w64-mingw32.tar.gz"
